export const TOGGLE_MODAL = 'TOGGLE_MODAL'

export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const CHANGE_PRODUCT_QUANTITY = 'CHANGE_PRODUCT_QUANTITY'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const HANDLE_QUANTITY_CHANGE = 'HANDLE_QUANTITY_CHANGE'

export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
